version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8089:8080'
      - '50000:50000'
    environment:
      - "JAVA_OPTS=-Duser.timezone=Asia/Shanghai -Xms512m -Xmx1024m -XX:MaxNewSize=512m"
    volumes:
      - './data:/var/jenkins_home'
      - '/etc/localtime:/etc/localtime'